name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    needs: build  # Ensure this job runs after the build job
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Prodction-files
          path: ./build
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN}}
          publish_dir: ./build
